[package]
name = "dash-router-core"
description = "The Dash Router protocol as a pure state machine, with no I/O"
version.workspace = true
edition.workspace = true

[dependencies]
polestar = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }

[patch."https://github.com/maackle/polestar-rs"]
polestar = { path = "/home/michael/proj/polestar-rs" }
