[package]
name = "dash-router-core"
description = "The Dash Router protocol as a pure state machine, with no I/O"
version.workspace = true
edition.workspace = true

[dependencies]
polestar = { workspace = true, features = ["serde"] }
anyhow = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
